### ISSUE TITLE
Табы с разными вариантами получения исходников

### ISSUE THREAD

**Issue by serhii73** [the-tale/tt_docs#10]
https://docs.the-tale.org/ru/stable/development/install.html#id2
Предлагаю создать табы `Clone with HTTPS` и `Clone with SSH` здесь:
```
git clone https://github.com/Tiendil/the-tale.git
git clone https://github.com/Tiendil/deworld.git
git clone https://github.com/Tiendil/dext.git
git clone https://github.com/Tiendil/questgen.git
```

**Comment by Tiendil** [comment]
Табы — в смысле переключения между двумя вариантами скачивания исходников?

Можно. Ну уверен, что restructured text такое умеет, но попробуй.

Только тогда не надо всю врезку команд дублировать, а выделить git clone в отдельный элемент и уже его переключать.

**Comment by Tiendil** [comment]
Табы работают, но поехала вёрска дальше (пропало оформление команд в блок кода)

**Comment by serhii73** [comment]
![Screenshot from 2019-07-13 16-07-39](https://user-images.githubusercontent.com/24910277/61172071-60391600-a588-11e9-90ef-f5c8d9e59655.png)
Сейчас без этого кода все выглядит вот так.
![Screenshot_2019-07-13 Установка и запуск — Документация «Сказка» 0 3 26](https://user-images.githubusercontent.com/24910277/61172134-1f8dcc80-a589-11e9-9f50-035df4c5e5e2.png)
могу добавить 
```
.. code-block:: bash
```
и будет вот так выглядеть. нормально?

**Comment by serhii73** [comment]
![Screenshot_2019-07-13 Установка и запуск — Документация «Сказка» 0 3 26](https://user-images.githubusercontent.com/24910277/61172190-a0e55f00-a589-11e9-9729-3d8b0c6c7b56.png)
Потому что, если бросто мой блок сдвинуть, чтобы все было под `.. code-block:: bash` - то будет выглядеть вот так.
